name: Build

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # pin@v3
      - uses: DeterminateSystems/nix-installer-action@de22e16c4711fca50c816cc9081563429d1cf563 # pin@main
        with:
          nix-installer-tag: v0.16.1 # https://github.com/DeterminateSystems/nix-installer/tags
      - uses: DeterminateSystems/magic-nix-cache-action@fc6aaceb40b9845a02b91e059ec147e78d1b4e41 # pin@main
      - uses: DeterminateSystems/flake-checker-action@17d9279de7f9bd959209d0b30ba7a04773141217 # pin@main
      - uses: cachix/cachix-action@6a9a34cdd93d0ae4b4b59fd678660efb08109f2f # pin@v12
        with:
          name: nathanregner-mealie-nix
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Run `nix version`
        run: nix --version
      - name: Run `nix flake check`
        run: nix flake check
