name: Build

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # pin@v3
      - uses: DeterminateSystems/nix-installer-action@5c49fa4feb9cc164719a4e7df4b56065cc9e4a91 # pin@main
        # with:
        #   nix-installer-tag: v0.16.1 # https://github.com/DeterminateSystems/nix-installer/tags
      - uses: DeterminateSystems/magic-nix-cache-action@ab33fc26afd4e9af0f46d7e366a54caf1ff09ca4 # pin@main
      - uses: DeterminateSystems/flake-checker-action@635e0f349080272cecb2dab35c403e4b8d736392 # pin@main
      - uses: cachix/cachix-action@6a9a34cdd93d0ae4b4b59fd678660efb08109f2f # pin@v12
        with:
          name: nathanregner-mealie-nix
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Run `nix version`
        run: nix --version
      - name: Run `nix flake check`
        run: nix flake check
